name=str(input("¡Hola! cual es tu nombre: " ))
print(f"¡{name}! Vamos a verificar si el 1er valor es mayor al 2do valor")
num1=int(input("Ingresa el primer valor "))
num2=int(input("Ingresa el segundo valor "))
resultado=(num1>num2)
print("El resultado es:",resultado)